[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "coerce_type"
dynamic = ["version"]
description = "A library providing tools to enforce type hints."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
authors = [
  {name = "Ben Konrad Meyer", email = "ben.k.meyer@gmail.com"}
]
maintainers = [
  {name = "Ben Konrad Meyer", email = "ben.k.meyer@gmail.com"}
]
license = "MIT"
license-files = ["LICENSE"]
keywords = ["annotations", "typecasting"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Natural Language :: German",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries"
]
[project.urls]
Repository = "https://github.com/reyemDarnok/coerce_type.git"
Issues = "https://github.com/reyemDarnok/coerce_type.git"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["src/coerce_type"]

[tool.hatch.envs.default.scripts]
all = [
  "hatch run lint:check",
  "hatch run lint:format",
  "hatch run test:test-cov",
  "hatch build"
]

[tool.hatch.envs.test]
dependencies = [
  "pytest",
  "pytest-cov", # Optional: for coverage reports
]
keep_env = true

[[tool.hatch.envs.test.matrix]]
python = [
  "3.10",
  "3.11",
  "3.12",
  "3.13",
  "3.14"]

[tool.hatch.envs.test.scripts]
test = "pytest {args:tests}"
test-cov = "pytest --cov=src/coerce_type {args:tests}"

[tool.hatch.envs.lint]
detached = true
dependencies = [
  "ruff",
]

[tool.hatch.envs.lint.scripts]
check = "ruff check {args:src tests} --fix"
format = "ruff format {args:src tests}"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"] # Error, Pyflakes, and Isort
ignore = ["E721"] # is and isinstance cannot replace get_origin